export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_NEXT_PAGE_URL = 'SET_NEXT_PAGE_URL';
export const SET_PREVIOUS_PAGE_URL = 'SET_PREVIOUS_PAGE_URL';
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE';
export const SET_SELECTED_POKEMON_DATA = 'SET_SELECTED_POKEMON_DATA';

